name: tests
on: [push, pull_request]
jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import check
        run: python - <<'PY'
from utils_tracker import normalize_columns, with_parsed_date, dedupe_last_then_sort_desc
print("✅ utils import OK")
PY
