# .streamlit/secrets.toml (primjer) — uklonite komentare i postavite svoje vrijednosti
# [GITHUB]
# token = "ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# repo = "ORG_ILI_USER/IME_REPOA"
# branch = "main"
# path = "data/Tracker.csv"
# committer_name = "Streamlit Bot"
# committer_email = "bot@example.com"
# csv_sep = ";"
