[GITHUB]
token = "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"   
repo = "vcorak86/location-tracking-HR-sales"
branch = "main"
path = "data/Tracker.csv"
committer_name = "Streamlit App (vcorak86)"  
committer_email = "vcorak86@users.noreply.github.com"
csv_sep = ";"
